# Generated by Django 6.0.3 on 2026-03-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['-created_at']},
        ),
    ]
